### ISSUE TITLE
[BUG] - Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by ksaitor** [premieroctet/next-admin#465]
### Description

![Screenshot 2024-10-04 at 09 43 50](https://github.com/user-attachments/assets/daa270a1-d3f6-4280-a902-0ed88a390efb)

### Reproduction URL

n/a

### Reproduction steps

```bash
1. Some of the prisma model pages throw this error
```

### Next router

Page router

### Next Admin version

6.1.4

### Next Admin options

```ts
initial clean setup. no custom options
```

### Logs

```bash
⨯ TypeError: Cannot read properties of undefined (reading 'length')
    at eval (webpack-internal:///./node_modules/@premieroctet/next-admin/dist/utils/server.js:357:52)
    at Array.forEach (<anonymous>)
    at findRelationInData (webpack-internal:///./node_modules/@premieroctet/next-admin/dist/utils/server.js:346:72)
    at mapDataList (webpack-internal:///./node_modules/@premieroctet/next-admin/dist/utils/prisma.js:312:77)
    at getMappedDataList (webpack-internal:///./node_modules/@premieroctet/next-admin/dist/utils/prisma.js:368:15)
    at async getPropsFromParams (webpack-internal:///./node_modules/@premieroctet/next-admin/dist/utils/props.js:88:48)
    at async getNextAdminProps (webpack-internal:///./node_modules/@premieroctet/next-admin/dist/pageRouter.js:17:19)
    at async eval (webpack-internal:///./pages/admin/[[...nextadmin]].tsx:37:12)
    at async withSuperJSON (file:///Users/.../node_modules/next-superjson-plugin/dist/tools.js:7:24)
    at async e8 (/Users/.../node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:25:124)
    at async doRender (/Users/.../node_modules/next/dist/server/base-server.js:1407:30)
    at async cacheEntry.responseCache.get.routeKind (/Users/.../node_modules/next/dist/server/base-server.js:1581:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/.../node_modules/next/dist/server/base-server.js:1489:28)
    at async DevServer.renderPageComponent (/Users/.../node_modules/next/dist/server/base-server.js:1913:24)
    at async DevServer.renderToResponseImpl (/Users/.../node_modules/next/dist/server/base-server.js:1951:32) {
  page: '/admin/article'
}
```
```


### Browsers

_No response_

**Comment by foyarash** [comment]
Hello @ksaitor , thanks for the report. Can you please let us know if this issue is fixed with v6.1.5 ?

If not, could you please send the following:

- impacted models
- Prisma version

Thank you !
