### ISSUE TITLE
[BUG] - Admin Panel Not Reflecting Prisma Schema Updates After Deploy on Vercel

### ISSUE THREAD

**Issue by setcubillos** [premieroctet/next-admin#490]
### Description

Hi everyone, how are you doing? I'm facing an issue, and I'm not sure if it's directly related to the framework or Vercel. When I update the schema in Prisma, for example, by adding a new model, after deploying to Vercel, the admin panel doesn’t reflect the changes. To make it work, I have to delete the app on Vercel and recreate it from scratch. In other words, it only detects the changes from the first deploy.

Does anyone have any idea why this might be happening or how to fix it? Thanks in advance!

![2024-11-28_11-12-34 (1)](https://github.com/user-attachments/assets/17f90e63-b3f4-450f-b881-e486da18dec8)

### Reproduction URL

https://github.com/setcubillos/web.rtms

### Reproduction steps

```bash
1. Update the schema on prisma
2. deploy de app to vercel
3. Observe that the Admin panel not display the changes
4. When ad a new model the Menu not display the new model(only on Prod)
```

### Next router

App router

### Next Admin version

7.0.1

### Screenshots

```bash
![DESCRIPTION]()
```

### Logs

```bash
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at <unknown> (/var/task/.next/server/chunks/47.js:1:700)
    at Array.map (<anonymous>)
    at <unknown> (/var/task/.next/server/chunks/47.js:1:671)
    at r (/var/task/.next/server/chunks/47.js:1:884)
    at k (/var/task/.next/server/app/admin/[[...nextadmin]]/page.js:14:205428)
    at ek (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:13409)
    at e (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:17307)
    at eO (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:17769)
    at eO (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:17944) {
  digest: '1238321692'
}
```

### Browsers

Chrome

**Comment by setcubillos** [comment]
**Description**
I encountered an issue when adding a new property, ranking, to the Involvement model. After updating the schema, I also included this property in my options file.

Here is an example of the update:
<img width="1278" alt="image" src="https://github.com/user-attachments/assets/4778e234-4627-4f05-b388-d87ffb1a340c">


The changes work perfectly in the local environment. However, in the production environment, the property does not seem to work as expected. Interestingly, if I comment out the line where the property is used, everything works fine in production.

**Steps to Reproduce**
Add a new property (ranking) to the Involvement model.
Update the options file to include the new property.
Deploy the changes to the production environment.

**Actual Behavior**
Locally: The changes work without issues.
Production: The application does not function as expected unless the new property (ranking) is commented out.
**Additional Information**
The issue only arises in the production environment, not locally.

**Comment by foyarash** [comment]
Hello @setcubillos ,

When you deploy to Vercel, are you running a script that pushes your schema to your database ? Through `prisma db push` or `prisma db migrate`

**Comment by setcubillos** [comment]
@setcubillos This is the script that are using 
<img width="780" alt="image" src="https://github.com/user-attachments/assets/4cdaef93-cc75-450e-a366-ade667ccf5f7">

**Comment by setcubillos** [comment]
Yes,  the database is updated contains the new field, but the option file not reconize the new property added, 
![image](https://github.com/user-attachments/assets/466a75c3-cd04-4138-a795-aaad4270ed3c)
As mentioned before if comment this line then working

**Comment by foyarash** [comment]
Thanks for the details, we will have a look

**Comment by setcubillos** [comment]
Hi @foyarash Just to let you know, I downgraded to version 6.1.8, to use the JSON schema generator and worked!
<img width="709" alt="image" src="https://github.com/user-attachments/assets/9022c94e-58c7-411c-a730-69d8509feb82">

**Comment by foyarash** [comment]
Thanks for this, guess we have an issue with the new generator then, we will investigate

**Comment by cregourd** [comment]
Hey @setcubillos 

Sorry for the delay, I come back to this issue, do you still have the issue ?
