### ISSUE TITLE
[BUG] - Doesn't work with src directory

### ISSUE THREAD

**Issue by dhruvwill** [premieroctet/next-admin#504]
### Description

while running the command `npx @premieroctet/next-admin-cli@latest init` throws error Schema file "D:\Projects\xyz\prisma\schema.prisma does not exist".

I am using nextjs src directory. 

i tried manually setting up the next-admin, but ran into issues. 
![image](https://github.com/user-attachments/assets/e0ee1d3c-eb75-4f97-ade2-97f395a6d262)

Note: I added generator to schema.prisma file. ran the generate command too, still the issue persists.

### Reproduction URL

notneeded

### Reproduction steps

```bash
-
```

### Next router

App router

### Next Admin version

7.1.0

### Next Admin options

```ts
import { NextAdmin, PageProps } from "@premieroctet/next-admin";
import { getNextAdminProps } from "@premieroctet/next-admin/appRouter";
// import { prisma } from "@/prisma";
import { db as prisma} from "@/lib/db";
// import "@/styles.css"; // .css file containing tailiwnd rules
import "@/app/globals.css"

export default async function AdminPage({ params, searchParams }: PageProps) {
  // or PromisePageProps for Next 15+
  const props = await getNextAdminProps({
    params: params.nextadmin,
    searchParams,
    basePath: "/admin",
    apiBasePath: "/api/admin",
    prisma,
    /*options*/
  });

  return <NextAdmin {...props} />;
}
```

### Logs

```bash
✓ Starting...
 ✓ Ready in 4.7s
 ○ Compiling /src/middleware ...
 ✓ Compiled /src/middleware in 7.6s (1189 modules)
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 GET /_next/static/webpack/d4ba8d2ff4150221.webpack.hot-update.json 404 in 9036ms
 ✓ Compiled in 1622ms (383 modules)
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 GET /_next/static/webpack/d4ba8d2ff4150221.webpack.hot-update.json 404 in 133ms
 ○ Compiling /admin/[[...nextadmin]] ...
 ⚠ ./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js
Module not found: Can't resolve '.next-admin/schema.json' in 'D:\Projects\cowrite\node_modules\.pnpm\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u\node_modules\@premieroctet\next-admin\dist\utils'

Import trace for requested module:
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/props.js
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/appRouter.js
./src/app/admin/[[...nextadmin]]/page.tsx
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 GET /_next/static/webpack/d4ba8d2ff4150221.webpack.hot-update.json 404 in 815ms
 GET /admin 200 in 11616ms
 ⨯ Error: Schema not found, make sure you added the generator to your schema.prisma file
    at getJsonSchema (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js:59:15)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js:62:22)
    at (rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js (D:\Projects\cowrite\.next\server\vendor-chunks\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u.js:1227:1)
    at __webpack_require__ (D:\Projects\cowrite\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/prisma.js:19:65)
    at (rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/prisma.js (D:\Projects\cowrite\.next\server\vendor-chunks\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u.js:1207:1)
    at __webpack_require__ (D:\Projects\cowrite\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/props.js:9:65)
    at (rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/props.js (D:\Projects\cowrite\.next\server\vendor-chunks\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u.js:1217:1)
    at __webpack_require__ (D:\Projects\cowrite\.next\server\webpack-runtime.js:33:43) {
  type: 'Error',
  page: '/admin'
}
 ⨯ Error: Schema not found, make sure you added the generator to your schema.prisma file
    at getJsonSchema (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js:59:15)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js:62:22)
    at (rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js (D:\Projects\cowrite\.next\server\vendor-chunks\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u.js:1227:1)
    at __webpack_require__ (D:\Projects\cowrite\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/prisma.js:19:65)
    at (rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/prisma.js (D:\Projects\cowrite\.next\server\vendor-chunks\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u.js:1207:1)
    at __webpack_require__ (D:\Projects\cowrite\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/props.js:9:65)
    at (rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/props.js (D:\Projects\cowrite\.next\server\vendor-chunks\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u.js:1217:1)
    at __webpack_require__ (D:\Projects\cowrite\.next\server\webpack-runtime.js:33:43) {
  type: 'Error',
  page: '/admin'
}
 ⚠ ./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js
Module not found: Can't resolve '.next-admin/schema.json' in 'D:\Projects\cowrite\node_modules\.pnpm\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u\node_modules\@premieroctet\next-admin\dist\utils'

Import trace for requested module:
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/props.js
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/appRouter.js
./src/app/admin/[[...nextadmin]]/page.tsx
 GET /admin 500 in 1467ms
 ⚠ ./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js
Module not found: Can't resolve '.next-admin/schema.json' in 'D:\Projects\cowrite\node_modules\.pnpm\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u\node_modules\@premieroctet\next-admin\dist\utils'

Import trace for requested module:
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/props.js
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/appRouter.js
./src/app/admin/[[...nextadmin]]/page.tsx
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 GET /admin 200 in 2137ms
 GET /_next/static/webpack/d4ba8d2ff4150221.webpack.hot-update.json 404 in 2237ms
 ⨯ Error: Schema not found, make sure you added the generator to your schema.prisma file
    at getJsonSchema (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js:59:15)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js:62:22)
    at (rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js (D:\Projects\cowrite\.next\server\vendor-chunks\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u.js:1227:1)
    at __webpack_require__ (D:\Projects\cowrite\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/prisma.js:19:65)
    at (rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/prisma.js (D:\Projects\cowrite\.next\server\vendor-chunks\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u.js:1207:1)
    at __webpack_require__ (D:\Projects\cowrite\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/props.js:9:65)
    at (rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/props.js (D:\Projects\cowrite\.next\server\vendor-chunks\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u.js:1217:1)
    at __webpack_require__ (D:\Projects\cowrite\.next\server\webpack-runtime.js:33:43) {
  type: 'Error',
  page: '/admin'
}
 ⨯ Error: Schema not found, make sure you added the generator to your schema.prisma file
    at getJsonSchema (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js:59:15)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js:62:22)
    at (rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js (D:\Projects\cowrite\.next\server\vendor-chunks\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u.js:1227:1)
    at __webpack_require__ (D:\Projects\cowrite\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/prisma.js:19:65)
    at (rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/prisma.js (D:\Projects\cowrite\.next\server\vendor-chunks\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u.js:1207:1)
    at __webpack_require__ (D:\Projects\cowrite\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/props.js:9:65)
    at (rsc)/./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/props.js (D:\Projects\cowrite\.next\server\vendor-chunks\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u.js:1217:1)
    at __webpack_require__ (D:\Projects\cowrite\.next\server\webpack-runtime.js:33:43) {
  type: 'Error',
  page: '/admin'
}
 GET /admin 500 in 1259ms
 ⚠ ./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js
Module not found: Can't resolve '.next-admin/schema.json' in 'D:\Projects\cowrite\node_modules\.pnpm\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u\node_modules\@premieroctet\next-admin\dist\utils'

Import trace for requested module:
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/props.js
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/appRouter.js
./src/app/admin/[[...nextadmin]]/page.tsx
 ⚠ ./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js
Module not found: Can't resolve '.next-admin/schema.json' in 'D:\Projects\cowrite\node_modules\.pnpm\@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u\node_modules\@premieroctet\next-admin\dist\utils'

Import trace for requested module:
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/server.js
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/utils/props.js
./node_modules/.pnpm/@premieroctet+next-admin@7.1.0_@prisma+client@6.1.0_prisma@6.1.0__@types+react-dom@18.3.1_@ty_ayfddcnai2ekb4z5zr6parc56u/node_modules/@premieroctet/next-admin/dist/appRouter.js
./src/app/admin/[[...nextadmin]]/page.tsx
 GET /favicon.ico 200 in 752ms
```

### Browsers

Chrome

**Comment by foyarash** [comment]
Hello,

Thanks for the issue, this might be related to pnpm. Would it be possible for you to quickly have a try with yarn ?
We'll have to make it work for pnpm if it works for yarn.

Thanks !

**Comment by zbeyens** [comment]
Same issue here with pnpm, maybe we should support `output` optoin in the generator?

**Comment by foyarash** [comment]
Would you be able to have a try with yarn ? I'd like to determine if the issue comes from pnpm or not

**Comment by foyarash** [comment]
Could you please try by upgrading @premieroctet/next-admin-generator-prisma to 0.0.2, and re-run the prisma generate command ?

**Comment by henrym** [comment]
@foyarash I had the same issue when I switched from npm to pnpm. Upgrading the generator to 0.0.2 has fixed it. Thanks

**Comment by zbeyens** [comment]
I confirm the fix, thanks!
