### ISSUE TITLE
[BUG] - type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by eng-ahmad-sameer** [premieroctet/next-admin#505]
### Description

An error happened when passing the "user" props in the `NextAdmin` component.

- How I pass the user prop:

```
user={{
          data: {
            name: loggedInUser.name!,
          },
          logout: async () => {
            "use server";
            await signOut();
          },
        }}
```

![image](https://github.com/user-attachments/assets/74e60416-a78e-409f-8a49-b12e49b8797c)

### Reproduction URL

n/a

### Reproduction steps

```bash
1. add user prop to the NextAdmin component.
```

### Next router

App router

### Next Admin version

^7.1.0

### Logs

```bash
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at Menu (webpack-internal:///(ssr)/./node_modules/@premieroctet/next-admin/dist/components/Menu.js:51:17)
    at Lazy
    at div
    at ColorSchemeProvider (webpack-internal:///(ssr)/./node_modules/@premieroctet/next-admin/dist/context/ColorSchemeContext.js:37:32)
    at Lazy
    at O (webpack-internal:///(ssr)/./node_modules/next-themes/dist/index.mjs:22:24)
    at z (webpack-internal:///(ssr)/./node_modules/next-themes/dist/index.mjs:17:48)
    at Lazy
    at I18nProvider (webpack-internal:///(ssr)/./node_modules/@premieroctet/next-admin/dist/context/I18nContext.js:15:25)
    at Lazy
    at ConfigProvider (webpack-internal:///(ssr)/./node_modules/@premieroctet/next-admin/dist/context/ConfigContext.js:22:11)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:242:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:347:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:158:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:153:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:228:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:367:11)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:242:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:347:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:158:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:153:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:228:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:367:11)
    at Lazy
    at div
    at UnreadMessagesProvider (webpack-internal:///(ssr)/./src/providers/unread-messages.tsx:13:35)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:242:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:347:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:158:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:153:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:228:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:367:11)
    at Lazy
    at div
    at $ea8dcbcb9ea1b556$export$323e4fc2fa4753fb (webpack-internal:///(ssr)/./node_modules/@react-aria/utils/dist/openLink.mjs:36:21)
    at div
    at $f57aed4a881a3485$var$OverlayContainerDOM (webpack-internal:///(ssr)/./node_modules/@react-aria/overlays/dist/useModal.mjs:64:54)
    at $f57aed4a881a3485$export$178405afcd8c5eb (webpack-internal:///(ssr)/./node_modules/@react-aria/overlays/dist/useModal.mjs:31:21)
    at $f57aed4a881a3485$export$bf688221f59024e5
    at $18f2051aff69b9bf$export$a54013f0d02a8f82 (webpack-internal:///(ssr)/./node_modules/@react-aria/i18n/dist/context.mjs:28:19)
    at NextUIProvider (webpack-internal:///(ssr)/./node_modules/@nextui-org/system/dist/chunk-OBF4GOTT.mjs:20:25)
    at NextUiProviders (webpack-internal:///(ssr)/./src/app/providers.tsx:15:28)
    at Lazy
    at SessionProvider (webpack-internal:///(ssr)/./node_modules/next-auth/react.js:238:13)
    at NextAuthProvider (webpack-internal:///(ssr)/./src/app/providers.tsx:28:29)
    at Lazy
    at body
    at html
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/app/ReactDevOverlay.js:87:9)
    at HotReload (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/app/hot-reloader-client.js:322:11)
    at Router (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:202:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:112:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:158:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:564:13)
    at Lazy
    at r6 (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:19018)
    at r6 (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:19018)
    at ServerInsertedHTMLProvider (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:24765)
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at Menu (webpack-internal:///(ssr)/./node_modules/@premieroctet/next-admin/dist/components/Menu.js:51:17)
    at Lazy
    at div
    at ColorSchemeProvider (webpack-internal:///(ssr)/./node_modules/@premieroctet/next-admin/dist/context/ColorSchemeContext.js:37:32)
    at Lazy
    at O (webpack-internal:///(ssr)/./node_modules/next-themes/dist/index.mjs:22:24)
    at z (webpack-internal:///(ssr)/./node_modules/next-themes/dist/index.mjs:17:48)
    at Lazy
    at I18nProvider (webpack-internal:///(ssr)/./node_modules/@premieroctet/next-admin/dist/context/I18nContext.js:15:25)
    at Lazy
    at ConfigProvider (webpack-internal:///(ssr)/./node_modules/@premieroctet/next-admin/dist/context/ConfigContext.js:22:11)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:242:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:347:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:158:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:153:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:228:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:367:11)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:242:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:347:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:158:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:153:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:228:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:367:11)
    at Lazy
    at div
    at UnreadMessagesProvider (webpack-internal:///(ssr)/./src/providers/unread-messages.tsx:13:35)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:242:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:347:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:158:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:153:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:228:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:367:11)
    at Lazy
    at div
    at $ea8dcbcb9ea1b556$export$323e4fc2fa4753fb (webpack-internal:///(ssr)/./node_modules/@react-aria/utils/dist/openLink.mjs:36:21)
    at div
    at $f57aed4a881a3485$var$OverlayContainerDOM (webpack-internal:///(ssr)/./node_modules/@react-aria/overlays/dist/useModal.mjs:64:54)
    at $f57aed4a881a3485$export$178405afcd8c5eb (webpack-internal:///(ssr)/./node_modules/@react-aria/overlays/dist/useModal.mjs:31:21)
    at $f57aed4a881a3485$export$bf688221f59024e5
    at $18f2051aff69b9bf$export$a54013f0d02a8f82 (webpack-internal:///(ssr)/./node_modules/@react-aria/i18n/dist/context.mjs:28:19)
    at NextUIProvider (webpack-internal:///(ssr)/./node_modules/@nextui-org/system/dist/chunk-OBF4GOTT.mjs:20:25)
    at NextUiProviders (webpack-internal:///(ssr)/./src/app/providers.tsx:15:28)
    at Lazy
    at SessionProvider (webpack-internal:///(ssr)/./node_modules/next-auth/react.js:238:13)
    at NextAuthProvider (webpack-internal:///(ssr)/./src/app/providers.tsx:28:29)
    at Lazy
    at body
    at html
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/app/ReactDevOverlay.js:87:9)
    at HotReload (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/app/hot-reloader-client.js:322:11)
    at Router (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:202:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:112:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:158:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:564:13)
    at Lazy
    at r6 (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:19018)
    at r6 (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:19018)
    at ServerInsertedHTMLProvider (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:24765)
 ⨯ Internal error: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at aw (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46775)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at aj (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at aC (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:52874)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50095)
    at aj (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at /home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42336
    at aw (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42822)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at aw (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:44769)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at aj (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at aC (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:52874)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50095)
    at aj (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at /home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42336
    at aw (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42822)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at aj (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at aC (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:52874)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50095)
    at aj (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at /home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42336
    at aw (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42822)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at aj (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at aC (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:52874)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50095)
    at aj (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at /home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42336
    at aw (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42822)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at aj (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at aC (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:52874)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50095)
    at aj (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at /home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42336
    at aw (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42822)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at aw (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42922)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at aj (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at /home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42336
    at aw (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42822)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at aj (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at /home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42336
    at aw (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42822)
    at a_ (/home/ahmad-sameer/Documents/Development/acquirewell-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
digest: "839688786"
```

### Browsers

Chrome

**Comment by foyarash** [comment]
Hello @eng-ahmad-sameer 

Does this occur without the user prop ?
The example app has been using this prop without any issue.

Looking at the source code of the error, it seems that its related to an incorrect ressource icon, could you maybe check if you are passing a correct name for your resources icons ?

**Comment by eng-ahmad-sameer** [comment]
- No it doesn't occur without user prop.
- i did not pass any custom icon resources.

**Comment by eng-ahmad-sameer** [comment]
This my next admin props:
'''

const props = await getNextAdminProps({
    params: params.nextadmin,
    searchParams,
    basePath: "/admin",
    apiBasePath: "/api/admin",
    prisma: db as any,
    options,
  });
'''

**Comment by foyarash** [comment]
Does this occur on a custom page or all pages ?

**Comment by eng-ahmad-sameer** [comment]
All pages.

**Comment by foyarash** [comment]
Ah looks like its because of an issue with the heroicons version.

Could you add the following resolution in your package.json and re-install ?

`"@heroicons/react": "2.1.5"`

**Comment by eng-ahmad-sameer** [comment]
@foyarash 
Thanks this fixes the issue!

**Comment by neutron92** [comment]
@SajeeTechi i have same issue https://github.com/premieroctet/next-admin/issues/642

**Comment by neutron92** [comment]
@foyarash
